version: '3.1'
services:
  stats-server:
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats

  stats-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "6541:5432"

  ewm-service:
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
